spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms
    username: root
    password: root
  mybatis:
    mapper-location: classpath*:mapper/*.xml
    config-location: classpath:mybatis-config.xml
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  messages:
    basename: Messages,sign
    cache-seconds: -1
    encoding: UTF-8
---
logging:
  file: /logs/cms.log

---
server:
  port: 8081
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat
---
flyway:
  check-location: true
  locations: classpath:db/migration
  enabled: true
  encoding: utf-8
  sql-migration-prefix: V
  sql-migration-suffix: .sql


